name: CI/CD

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v3

            # Install dependencies
            - name: Install dependencies
              run: yarn

            # Build project
            - name: build project
              run: yarn build

            - name: Deploy to Server 1
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
                  REMOTE_HOST: ${ { secrets.HOST_DNS }}
                  REMOTE_USER: ${ { secrets.USERNAME }}
                  TARGET: ${ { secrets.TARGET_DIR }}
